### PR TITLE
Feature/ps 37 save discord webhook url to database

### PR DESCRIPTION
**Pull request by AyserJamshidi**

### CODE REVIEW

**Comment by AyserJamshidi** [comment]
Integration details:
PUT http://localhost:5000/webaccount/integration
```json
{
    "webaccount": {
        "webaccount_id": 4
    },
    "integration_type": "DISCORD",
    "data": "this_is_data"
}```

You may modify **integration_type** to any of the three social platforms.  Ensure it is in all caps.  **webaccount** value is most likely to change in the future as frontend has not finalized desired return values from endpoint.

**Review by apsawicki — CHANGES_REQUESTED** [review]
put some javadocs comments on IntegrationBean, WebAccountBean, and the enum

**Comment by AyserJamshidi** [comment]
> put some javadocs comments on IntegrationBean, WebAccountBean, and the enum

Requested changes have been made. Ready for review.

**Review by apsawicki — APPROVED** [review]
LGTM

**Pull request merged**
